### ISSUE TITLE
Examples and Readme is outdated

### ISSUE THREAD

**Issue by tengkuizdihar** [kardeiz/awmp#14]
Right now the readme and the example given in the project is outdated. For example (at least when using actix v3), the example given when using the code given will not work, knowing that the function `awmp::Parts::confgure` doesn't exist. Below are the example as of right now.

```
actix_web::HttpServer::new(move || {
        actix_web::App::new()
            .data(awmp::Parts::configure(|cfg| cfg.with_file_limit(1_000_000)))
            .route("/", actix_web::web::post().to(upload))
    })
```

After reading a bit of the code in `lib.rs`, it seems that the right approach should be as shown (i've tested it in my application).

```
actix_web::HttpServer::new(move || {
        actix_web::App::new()
            .data(awmp::PartsConfig::default().with_file_limit(1_000_000))
            .route("/", actix_web::web::post().to(upload))
    })
```

I would suggest to update the examples given and the readme too and would gladly give a PR when needed for this.

**Comment by kardeiz** [comment]
@tengkuizdihar `Parts::configure` is provided by `actix_web::FromRequest` and should be available and working for actix-web v3 as long as you have a `use actix_web::FromRequest;` in scope (as is done in the README and examples).

**Comment by tengkuizdihar** [comment]
My bad, I'm not aware of the `configure` method in FromRequest. Closing the issue.
