### ISSUE TITLE
Undocumented Behavior Invalid Cross-Device Link

### ISSUE THREAD

**Issue by tengkuizdihar** [kardeiz/awmp#15]
OS: Linux
Hard Drive Partitioning (it would be necessary for this issue): /tmp and /home is in a different partition.

There's a unique behavior shown when using this library and it might be caused by the usage of `tempfile` library. For example, given the code for handling file below:

```rust
let file = parts
    .files
    .take("file")
    .pop()
    .and_then(|f| {
        debug!("Sanitized filename: {}", f.sanitized_file_name());
        let result = f.persist_in("./storage");
        debug!("File after persist status: {:?}", result);
        result.ok()
    })
    .map(|f| debug!("File uploaded to: {}", f.display()))
    .unwrap_or_default();
```

and the parts config configuration as shown when building the actix app:

```rust
App::new()
    ...
    .data(
        PartsConfig::default()
            .with_file_limit(5_000_000)
            .with_text_limit(5_000_000)
            .with_temp_dir("/tmp"),
    );
```

When you're uploading a file with multipart, these error were instead shown.

```
Err(TempFilePersistError(PersistError { error: Os { code: 18, kind: Other, message: "Invalid cross-device link" }, file: NamedTempFile("/tmp/.tmpjsc2pf") }))
```

It seems to be that `tempfile` is using a hardlink when transfering the file from one place to another. In my opinion, even when it's quite niche, it should be documented that this behavior exist. My solution right now is to put the temporary directory in the same root directory of the project. For example, creating a new `storage` folder that's included in the .gitignore of the project.

```
App::new()
    ...
    .data(
        PartsConfig::default()
            .with_file_limit(5_000_000)
            .with_text_limit(5_000_000)
            .with_temp_dir("./storage"),
    );
```

Of course this solution is only good for development only and the user (the one who's deploying the server) should be able to modify `./storage` through environment variable, for example. I know that my solution isn't perfect and would be glad to discuss it further.

**Comment by kardeiz** [comment]
@tengkuizdihar Thanks for the issue! This is documented in the `tempfile` docs (https://docs.rs/tempfile/3.2.0/tempfile/struct.NamedTempFile.html#method.persist).

Your solution is fine, and this scenario is one of the main reasons `with_temp_dir` is provided.

I do think others may run into this, and I would be happy to merge a PR that improved the docs around this (probably `awmp::File::persist_in`, `awmp::File::persist_at`, and `awmp::PartsConfig::with_temp_dir`).

**Comment by tengkuizdihar** [comment]
Noted, thank you for the response
I'm happy that you're still actively developing something, even if its doesn't revolves around this library :)

**Comment by tengkuizdihar** [comment]
I've created a PR about the documentation in #16
