### ISSUE TITLE
Missing method to create a fake awmp::File

### ISSUE THREAD

**Issue by tengkuizdihar** [kardeiz/awmp#17]
Right now I have a problem where I need to create a fake awmp::File for testing purposes. I propose to create a new method in `File` to solve this problem. As far as I'm concerned, the implementation itself should be trivial and I would love to make a PR for it.

If there's any other solution or feedback regarding this problem, I would love to hear it.

**Comment by kardeiz** [comment]
Sounds good to me! I would suggest creating a constructor that takes a filename and either file bytes or a `NamedTempFile`. Please don't just `pub` the fields.

**Comment by tengkuizdihar** [comment]
Thank you for the reply! As of right now, the user doesn't have the ability to use `NamedTempFile`, if I use the second solution, should I also make that struct public?

**Comment by tengkuizdihar** [comment]
I've made a pull request on #18 with test and two ways to create a `awmp::File`.
