### ISSUE TITLE
no function or associated item named `configure` found for struct `awmp::Parts` in the current scope

### ISSUE THREAD

**Issue by ctopher7** [kardeiz/awmp#5]
using v2

**Comment by kardeiz** [comment]
`awmp::Parts::configure` is provided by `actix_web::FromRequest`, so make sure you have 
```rust
use actix_web::FromRequest;
```
in this scope. If that doesn't help, please include your full error here. Thanks!

**Comment by ctopher7** [comment]
@kardeiz my bad, thank you for the help! it works
